version: '3.8'
services:
  zookeeper-node-1:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-node-1:2888:3888;zookeeper-node-2:2888:3888
    ports:
      - 12181:12181

  zookeeper-node-2:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-node-1:2888:3888;zookeeper-node-2:2888:3888
    ports:
      - 22181:22181

  kafka-node-1:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper-node-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node-1:12181,zookeeper-node-2:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node-1:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-node-2:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper-node-1
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node-1:12181,zookeeper-node-2:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node-2:19093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-node-3:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper-node-1
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node-1:12181,zookeeper-node-2:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node-3:19094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1